// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UNI.Domain;

#nullable disable

namespace UNI.Persistence.Migrations
{
    [DbContext(typeof(UniDbContext))]
    [Migration("20220926201054_addedAllCI")]
    partial class addedAllCI
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UNI.Domain.ContactInfo", b =>
                {
                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("ContactsInfo");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "Copenhagen, Denmark",
                            Email = "hejlsberg@gmail.com",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "USA",
                            Email = "allen@gmail.com",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 3,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 4,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 5,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 6,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 7,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 8,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 9,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 10,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 11,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 12,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 13,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 14,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 15,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 16,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 17,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 18,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 19,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 20,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 21,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 22,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 23,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 24,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 25,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 26,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 27,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 28,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 29,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 30,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 31,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 32,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 33,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 34,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 35,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 36,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 37,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 38,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 39,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 40,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 41,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        },
                        new
                        {
                            StudentId = 42,
                            Address = "adress",
                            Email = "email",
                            PhoneNumber = "101010101010"
                        });
                });

            modelBuilder.Entity("UNI.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CourseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlCoursLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseDescription = "Learn how to write high performance and scalable .NET Core and ASP.NET Core applications in C#",
                            CourseName = ".Net Developer",
                            UrlCoursLogo = "https://dotnetfoundation.org/img/dot_bot.png"
                        },
                        new
                        {
                            Id = 2,
                            CourseDescription = "Become a confident industry ready core Java developer and get certified as a Java professional!",
                            CourseName = "Java Developer",
                            UrlCoursLogo = "https://www.whatap.io/ko/blog/12/img/java_history.webp"
                        },
                        new
                        {
                            Id = 3,
                            CourseDescription = "Practical course for QA testers",
                            CourseName = "Automation QA",
                            UrlCoursLogo = "https://brainup.space/wp-content/uploads/2021/09/qa-engineer-300x300.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CourseDescription = "Learn Python like a Professional Start from the basics and go all the way to creating your own applications",
                            CourseName = "Python Developer",
                            UrlCoursLogo = "https://contentstatic.techgig.com/photo/88317143/how-and-why-to-become-a-certified-python-programmer-in-2022.jpg?116970"
                        },
                        new
                        {
                            Id = 5,
                            CourseDescription = "From Complete Beginner To Professional Game Developer. Learn To Code In C# And Create Stunning Games With Unity",
                            CourseName = "Unity Developer",
                            UrlCoursLogo = "https://gagadget.com/media/post_big/unity-best-tools-january-2022-800x449.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CourseDescription = "Everything you need to transition from hobbyist to professional iOS developer",
                            CourseName = "iOS Developer",
                            UrlCoursLogo = "https://media-exp2.licdn.com/dms/image/C510BAQEeZG6Lx64row/company-logo_200_200/0/1543775201739?e=2147483647&v=beta&t=oJqpcDJZIr5ypO0gV9fN3O0M224JdKCTDQUFwgpHHEE"
                        },
                        new
                        {
                            Id = 7,
                            CourseDescription = "Get advanced with Node.Js! Learn caching with Redis, speed up through clustering, and add image upload with S3 and Node!",
                            CourseName = "Node js",
                            UrlCoursLogo = "https://cdn.iconscout.com/icon/free/png-256/node-js-3550841-2970426.png"
                        },
                        new
                        {
                            Id = 8,
                            CourseDescription = "Launch a career as a web designer by learning HTML5, CSS3, responsive design, Sass and more!",
                            CourseName = "WEB Designer",
                            UrlCoursLogo = "https://www.varnitec.com/sites/default/files/2020-06/2.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CourseDescription = "Build a real e-commerce app with Angular, Firebase and Bootstrap 4",
                            CourseName = "Angular",
                            UrlCoursLogo = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZoqNQ3pxtbGCECwyUcKbiHK9lbeW86ZBmqJ9HOBBsBBrjq9OmSfxppeT6_O5CCJKnk50&usqp=CAU"
                        });
                });

            modelBuilder.Entity("UNI.Domain.Entities.Course_Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("GroupId");

                    b.ToTable("Courses_Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            GroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 7,
                            GroupId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            GroupId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 9,
                            GroupId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            GroupId = 3
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 7,
                            GroupId = 3
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 2,
                            GroupId = 4
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 9,
                            GroupId = 4
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 7,
                            GroupId = 5
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 4,
                            GroupId = 5
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 9,
                            GroupId = 6
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 4,
                            GroupId = 6
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 1,
                            GroupId = 7
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 2,
                            GroupId = 8
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 4,
                            GroupId = 9
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 1,
                            GroupId = 10
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 5,
                            GroupId = 10
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 5,
                            GroupId = 11
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 4,
                            GroupId = 12
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 3,
                            GroupId = 12
                        },
                        new
                        {
                            Id = 21,
                            CourseId = 3,
                            GroupId = 13
                        },
                        new
                        {
                            Id = 22,
                            CourseId = 2,
                            GroupId = 13
                        },
                        new
                        {
                            Id = 23,
                            CourseId = 3,
                            GroupId = 14
                        },
                        new
                        {
                            Id = 24,
                            CourseId = 8,
                            GroupId = 15
                        },
                        new
                        {
                            Id = 25,
                            CourseId = 7,
                            GroupId = 16
                        },
                        new
                        {
                            Id = 26,
                            CourseId = 9,
                            GroupId = 17
                        },
                        new
                        {
                            Id = 27,
                            CourseId = 6,
                            GroupId = 18
                        });
                });

            modelBuilder.Entity("UNI.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupName = ".Net Developer+Node.js",
                            Speciality = "FullStack Developer"
                        },
                        new
                        {
                            Id = 2,
                            GroupName = ".Net Developer+Angular",
                            Speciality = "FullStack Developer"
                        },
                        new
                        {
                            Id = 3,
                            GroupName = "Java Developer+Node.js",
                            Speciality = "FullStack Developer"
                        },
                        new
                        {
                            Id = 4,
                            GroupName = "Java Developer+Angular",
                            Speciality = "FullStack Developer"
                        },
                        new
                        {
                            Id = 5,
                            GroupName = "Python Developer+Node.js",
                            Speciality = "FullStack Developer"
                        },
                        new
                        {
                            Id = 6,
                            GroupName = "Python Developer+Angular",
                            Speciality = "FullStack Developer"
                        },
                        new
                        {
                            Id = 7,
                            GroupName = ".Net Developer",
                            Speciality = ".Net Developer"
                        },
                        new
                        {
                            Id = 8,
                            GroupName = "Java Developer",
                            Speciality = "Java Developer"
                        },
                        new
                        {
                            Id = 9,
                            GroupName = "Python Developer",
                            Speciality = "Python Developer"
                        },
                        new
                        {
                            Id = 10,
                            GroupName = "Unity Developer + C#",
                            Speciality = "Unity Developer"
                        },
                        new
                        {
                            Id = 11,
                            GroupName = "Unity Developer",
                            Speciality = "Unity Developer"
                        },
                        new
                        {
                            Id = 12,
                            GroupName = "Python Developer + Automation QA",
                            Speciality = "Python Developer"
                        },
                        new
                        {
                            Id = 13,
                            GroupName = "Java Developer+Automation QA",
                            Speciality = "Java Developer"
                        },
                        new
                        {
                            Id = 14,
                            GroupName = "Automation QA",
                            Speciality = "Automation QA"
                        },
                        new
                        {
                            Id = 15,
                            GroupName = "WEB Designer",
                            Speciality = "WEB Designer"
                        },
                        new
                        {
                            Id = 16,
                            GroupName = "Node js",
                            Speciality = "Node js"
                        },
                        new
                        {
                            Id = 17,
                            GroupName = "Angular",
                            Speciality = "Angular"
                        },
                        new
                        {
                            Id = 18,
                            GroupName = "iOS Developer",
                            Speciality = "iOS Developer"
                        });
                });

            modelBuilder.Entity("UNI.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlStudentPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Anders",
                            GroupId = 1,
                            LastName = "Hejlsberg",
                            UrlStudentPhoto = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Anders_Hejlsberg.jpg/274px-Anders_Hejlsberg.jpg"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Scott",
                            GroupId = 1,
                            LastName = "Allen",
                            UrlStudentPhoto = "https://odetocode.com/Images/scott_allen_7.jpg"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Iris",
                            GroupId = 1,
                            LastName = "Classon",
                            UrlStudentPhoto = "https://www.irisclasson.com/promo/irisclasson.jpg.webp"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "David",
                            GroupId = 1,
                            LastName = "Ebbo",
                            UrlStudentPhoto = "http://www.gravatar.com/avatar/3c4e7f8b11f8b8c1d77ebb70678097b4?s=128?s=160"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Damian",
                            GroupId = 2,
                            LastName = "Edwards",
                            UrlStudentPhoto = "https://0.gravatar.com/avatar/069d9cb18fdf2956b0dcee852627fb08?s=96&d=https%3A%2F%2F0.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D96"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "David",
                            GroupId = 2,
                            LastName = "Fowler",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1320061631339126786/gHKfzYft_400x400.jpg"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Jon",
                            GroupId = 2,
                            LastName = "Galloway",
                            UrlStudentPhoto = "https://w2nxbg.dm.files.1drv.com/y4mvd6G94DdTBVbUzRoqINo7FzA9RdXOFwI8vti_JD1lLw5klF3xHr4YRQTCYdgmpN6uz4DH6kjre4vcifzLJiHCbraAzlXyT7KCzXczoGidr3d5wH5K-p8wccuOUzkeU4_gcr_GnIciHN1KX2qgdBCDZMcXDUwKlGMLse3cjUO4pFcJ5bZY9JtpmV35mmCSd8Y?width=1400&height=1668&cropmode=none"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Scott",
                            GroupId = 7,
                            LastName = "Guthrie",
                            UrlStudentPhoto = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/MIX_Keynote-Scott_Guthrie_09_MS_05_2007.jpg/250px-MIX_Keynote-Scott_Guthrie_09_MS_05_2007.jpg"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "",
                            GroupId = 7,
                            LastName = "",
                            UrlStudentPhoto = "https://2.gravatar.com/avatar/cdf546b601bf29a7eb4ca777544d11cd?s=160"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Phil",
                            GroupId = 7,
                            LastName = "Haack",
                            UrlStudentPhoto = "https://user-images.githubusercontent.com/19977/108404639-f3124b80-71d4-11eb-925e-1de429de32e4.jpg"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Corey",
                            GroupId = 10,
                            LastName = "Haines",
                            UrlStudentPhoto = "http://1.bp.blogspot.com/-TdAHPTfmQzs/US_PBudX1GI/AAAAAAAAEbY/riZfOb5Zi2U/s200/fullheadmullet.jpg"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Drew",
                            GroupId = 10,
                            LastName = "Marsh",
                            UrlStudentPhoto = "https://hackedbrain.blob.core.windows.net/wp-blog-content/2021/10/Annotation-2019-08-23-164228-300x269.jpg"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "John",
                            GroupId = 1,
                            LastName = "Papa",
                            UrlStudentPhoto = "https://res.cloudinary.com/practicaldev/image/fetch/s--Xf3zlwar--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/138665/cee5c68d-3bd2-4042-af64-5214952d6c30.jpg"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Rick",
                            GroupId = 10,
                            LastName = "Strahl",
                            UrlStudentPhoto = "http://weblog.west-wind.com/images/rick175x175.jpg"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Arun",
                            GroupId = 3,
                            LastName = "Gupta",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1129247222925746178/lWdezfZX_400x400.jpg"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Markus",
                            GroupId = 3,
                            LastName = "Eisele",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1543194332320206853/yTEVsjGz_400x400.jpg"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Mark",
                            GroupId = 3,
                            LastName = "Reinhold",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1012167014612267010/tpIWebKt_400x400.jpg"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Adam",
                            GroupId = 4,
                            LastName = "Bien",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/82608077/abien_icon_400x400.jpg"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Simon",
                            GroupId = 4,
                            LastName = "Maple",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/618367538016178176/AoS8svVQ_400x400.jpg"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "David",
                            GroupId = 4,
                            LastName = "Blevins",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/860618035521912832/bS8OJGpX_400x400.jpg"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Reza",
                            GroupId = 8,
                            LastName = "Rahman",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1324902443923206152/C7cYJaIy_400x400.jpg"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Josh",
                            GroupId = 8,
                            LastName = "Juneau",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1646931434/jj-smaller_400x400.jpg"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Ken",
                            GroupId = 8,
                            LastName = "Fogel",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1181905040736436224/1ypGgL71_400x400.jpg"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Tim",
                            GroupId = 18,
                            LastName = "Cook",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1535420431766671360/Pwq-1eJc_400x400.jpg"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Chris",
                            GroupId = 18,
                            LastName = "Lattner",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1484209565788897285/1n6Viahb_400x400.jpg"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Ash",
                            GroupId = 18,
                            LastName = "Furrow",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1264707114179723275/c9U307g7_400x400.jpg"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Ole",
                            GroupId = 18,
                            LastName = "Begemann",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1414976054398267396/icGRwR9__400x400.jpg"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Chris",
                            GroupId = 18,
                            LastName = "Eidhof",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/496291231690137600/TmQRrofs_400x400.jpeg"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Mattt",
                            GroupId = 18,
                            LastName = "Thompson",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/969321564050112513/fbdJZmEh_400x400.jpg"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Ray",
                            GroupId = 18,
                            LastName = "Wenderlich",
                            UrlStudentPhoto = "https://pbs.twimg.com/profile_images/1380194129645297665/2OEX5bun_400x400.jpg"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Guido",
                            GroupId = 5,
                            LastName = "Rossum",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/Guido-van-Rossum.jpg"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Ewa",
                            GroupId = 5,
                            LastName = "Jodlowska",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/Ewa-Jodlowska.jpg"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Kevin",
                            GroupId = 5,
                            LastName = "Goldsmith",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/Kevin-Goldsmith.jpg"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Jen",
                            GroupId = 6,
                            LastName = "Walraven",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/Jen-Walraven.jpeg"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Audrey",
                            GroupId = 6,
                            LastName = "Greenfield",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/audrey_roy_greenfield.jpeg"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Daniel",
                            GroupId = 6,
                            LastName = "Greenfield",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/Daniel-Roy-Greenfeld.jpeg"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Reshama",
                            GroupId = 9,
                            LastName = "Shaikh",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/Reshama-Shaikh.jpg"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Tomaz",
                            GroupId = 9,
                            LastName = "Muraus",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/Tomaz-Muraus.jpg"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Tom",
                            GroupId = 9,
                            LastName = "Christie",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/tom_christie.jpg"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Yury",
                            GroupId = 12,
                            LastName = "Selivanov",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/Yury-Selivanov.jpg"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Raymond",
                            GroupId = 12,
                            LastName = "Hettinger",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/Raymond-Hettinger.jpg"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Łukasz",
                            GroupId = 12,
                            LastName = "Langa",
                            UrlStudentPhoto = "https://newrelic.com/sites/default/files/wp_blog_inline_files/Lukasz-Langa.png"
                        });
                });

            modelBuilder.Entity("UNI.Domain.ContactInfo", b =>
                {
                    b.HasOne("UNI.Domain.Entities.Student", "Student")
                        .WithOne("ContactInfo")
                        .HasForeignKey("UNI.Domain.ContactInfo", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UNI.Domain.Entities.Course_Group", b =>
                {
                    b.HasOne("UNI.Domain.Entities.Course", "Course")
                        .WithMany("Course_Groups")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNI.Domain.Entities.Group", "Group")
                        .WithMany("Course_Groups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UNI.Domain.Entities.Student", b =>
                {
                    b.HasOne("UNI.Domain.Entities.Group", "Group")
                        .WithMany("ListOfStudents")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UNI.Domain.Entities.Course", b =>
                {
                    b.Navigation("Course_Groups");
                });

            modelBuilder.Entity("UNI.Domain.Entities.Group", b =>
                {
                    b.Navigation("Course_Groups");

                    b.Navigation("ListOfStudents");
                });

            modelBuilder.Entity("UNI.Domain.Entities.Student", b =>
                {
                    b.Navigation("ContactInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
